# Generated by Django 5.2.11 on 2026-02-28 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('notebook_file', models.FileField(help_text='Upload a .ipynb Jupyter Notebook file.', upload_to='notebooks/files/%Y/%m/')),
                ('rendered_html', models.TextField(blank=True, help_text='Auto-generated HTML from the notebook.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='notebooks/images/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='notebooks', to='core.tag')),
            ],
            options={
                'verbose_name': 'Notebook Visualization',
                'verbose_name_plural': 'Notebook Visualizations',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_comments', to=settings.AUTH_USER_MODEL)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notebooks.notebookvisualization')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.AddIndex(
            model_name='notebookvisualization',
            index=models.Index(fields=['-published_date'], name='notebooks_n_publish_bbaf74_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_date'], name='notebooks_c_created_7e914a_idx'),
        ),
    ]
